---
- hosts: docker
  vars:
    docker_daemon_config:
      hosts:
        - unix:///var/run/docker.sock
        - tcp://0.0.0.0:2375
    docker_users:
      - vagrant
  roles:
    - haxorof.docker-ce